package com.plub.domain.model.enums

enum class DialogMenuItemType {
    CAMERA_IMAGE, ALBUM_IMAGE, DEFAULT_IMAGE,
    SORT_TYPE_NEW, SORT_TYPE_POPULAR,
    BOARD_EDIT, BOARD_DELETE, BOARD_REPORT, BOARD_FIX_CLIP, BOARD_RELEASE_CLIP, BOARD_FIX_OR_RELEASE_CLIP,
    BOARD_COMMENT_DELETE, BOARD_COMMENT_EDIT, BOARD_COMMENT_REPORT,
    SCHEDULE_EDIT, SCHEDULE_DELETE
}