package com.plub.domain.model.enums

enum class DialogMenuType {
    IMAGE,
    IMAGE_HAS_DEFAULT,
    SORT_TYPE,
    BOARD_AUTHOR_TYPE, BOARD_COMMON_TYPE,
    BOARD_LIST_HOST_TYPE, BOARD_LIST_HOST_AND_AUTHOR_TYPE,
    BOARD_CLIP_HOST_TYPE, BOARD_CLIP_HOST_AND_AUTHOR_TYPE,
    BOARD_DETAIL_HOST_TYPE, BOARD_DETAIL_HOST_AND_AUTHOR_TYPE,
    BOARD_COMMENT_FEED_AUTHOR_TYPE, BOARD_COMMENT_AUTHOR_TYPE,
    BOARD_COMMENT_COMMON_TYPE,
    SCHEDULE_TYPE
}