package com.plub.domain.model.enums

enum class DialogMenuType {
    IMAGE,
    IMAGE_HAS_DEFAULT,
    SORT_TYPE,
    BOARD_AUTHOR_TYPE, BOARD_COMMON_TYPE,
    BOARD_LIST_HOST_TYPE, BOARD_LIST_HOST_AND_AUTHOR_TYPE,
    BOARD_CLIP_HOST_TYPE, BOARD_CLIP_HOST_AND_AUTHOR_TYPE,
    BOARD_DETAIL_HOST_TYPE, BOARD_DETAIL_HOST_AND_AUTHOR_TYPE,
    BOARD_COMMENT_FEED_AUTHOR_TYPE, BOARD_COMMENT_AUTHOR_TYPE,
    BOARD_COMMENT_COMMON_TYPE,
    SCHEDULE_TYPE,
    TODO_LIST_COMMON_TYPE,
    TODO_LIST_AUTHOR_TYPE,
    TODO_PLANNER_UNCHECKED_TYPE, TODO_PLANNER_CHECKED_PROOFED_TYPE, TODO_PLANNER_CHECKED_NOT_PROOFED_TYPE,
    TODO_DETAIL_COMMON_TYPE, TODO_DETAIL_AUTHOR_CHECKED_NOT_PROOFED_TYPE, TODO_DETAIL_AUTHOR_COMMON_TYPE,
    ARCHIVE_HOST_TYPE, ARCHIVE_AUTHOR_TYPE, ARCHIVE_NORMAL_TYPE,
    PLUBING_NOTICE_HOST_TYPE, PLUBING_NOTICE_COMMON_TYPE,
    NOTICE_COMMENT_NOTICE_AUTHOR_TYPE, NOTICE_COMMENT_AUTHOR_TYPE,
    NOTICE_COMMENT_COMMON_TYPE,
}